version: '3'
services:
  app:
    build:
      context: ./app
    container_name: express-app
    ports:
      - '3000:3000'
    volumes:
      - './app:/usr/src/app'

  web:
    image: nginx:latest #nginx:alpilneだとエラーが起きる
    container_name: nginx-web
    ports:
      - '80:80'
    volumes:
      - './web/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf'
    links:
      - app
    depends_on:
      - app
